apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digitrans

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - auth-gateway.yaml
  - erp-service.yaml
  - crm-service.yaml
  - supply-chain-service.yaml
  - bi-service.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  project: digitrans-cm
  managed-by: kustomize
